"""empty message

Revision ID: 29336c8f4c0f
Revises: 6a8c5334db66
Create Date: 2022-08-12 11:30:02.924348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29336c8f4c0f'
down_revision = '6a8c5334db66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venuelists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('vList_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'venuelists', ['vList_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'vList_id')
    op.drop_table('venuelists')
    # ### end Alembic commands ###
