"""empty message

Revision ID: 297dad6b5aee
Revises: 7d74104c3af7
Create Date: 2022-08-15 23:53:12.319632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297dad6b5aee'
down_revision = '7d74104c3af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('aList_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'artistlists', ['aList_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'aList_id')
    op.drop_table('Show')
    op.drop_table('artistlists')
    # ### end Alembic commands ###
