"""empty message

Revision ID: 6211652021cf
Revises: 29336c8f4c0f
Create Date: 2022-08-13 17:41:32.205879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6211652021cf'
down_revision = '29336c8f4c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venuelists', sa.Column('city', sa.String(), nullable=False))
    op.add_column('venuelists', sa.Column('state', sa.String(), nullable=False))
    op.drop_column('venuelists', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venuelists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('venuelists', 'state')
    op.drop_column('venuelists', 'city')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
